// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1vjltDrFo18uqhmFdB7GuRxvhGJ5N3Ew',
    appId: '1:504780517025:web:0a225bf9befc60ecc70ae0',
    messagingSenderId: '504780517025',
    projectId: 'task10-auth-ff2c1',
    authDomain: 'task10-auth-ff2c1.firebaseapp.com',
    storageBucket: 'task10-auth-ff2c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfp4bVQn_STIUC0LsRwfXfQtLlgIfMvl8',
    appId: '1:504780517025:android:0c07091031844ee9c70ae0',
    messagingSenderId: '504780517025',
    projectId: 'task10-auth-ff2c1',
    storageBucket: 'task10-auth-ff2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-PuOKW-yqF-4_k38MFZyuWxEs0CbyeGQ',
    appId: '1:504780517025:ios:ed8f5751152140b9c70ae0',
    messagingSenderId: '504780517025',
    projectId: 'task10-auth-ff2c1',
    storageBucket: 'task10-auth-ff2c1.firebasestorage.app',
    iosBundleId: 'com.example.task10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-PuOKW-yqF-4_k38MFZyuWxEs0CbyeGQ',
    appId: '1:504780517025:ios:ed8f5751152140b9c70ae0',
    messagingSenderId: '504780517025',
    projectId: 'task10-auth-ff2c1',
    storageBucket: 'task10-auth-ff2c1.firebasestorage.app',
    iosBundleId: 'com.example.task10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1vjltDrFo18uqhmFdB7GuRxvhGJ5N3Ew',
    appId: '1:504780517025:web:da98713a573a6b1bc70ae0',
    messagingSenderId: '504780517025',
    projectId: 'task10-auth-ff2c1',
    authDomain: 'task10-auth-ff2c1.firebaseapp.com',
    storageBucket: 'task10-auth-ff2c1.firebasestorage.app',
  );

}